steps:
    - id: 'run-docker-compose'
      name: 'gcr.io/$PROJECT_ID/docker-compose:latest'
      args: ['-f', 'docker-compose.cloudbuild.yaml', 'up', '-d']
    - id: 'run-docker-ps'
      name: 'gcr.io/cloud-builders/docker'
      waitFor: ['run-docker-compose']
      args: ['ps']
    - id: 'run-tests'
      name: 'gcr.io/cloud-builders/docker'
      waitFor: ['run-docker-compose', 'run-docker-ps']
      args: ['exec', '-t', 'gcb-pipelines', 'yarn', 'test']