steps:
    - id: "Run docker-compose"
      name: 'gcr.io/$PROJECT_ID/docker-compose:latest'
      args: ['-f', 'docker-compose.cloudbuild.yaml', 'up', '-d']
    - id: "Run docker ps"
      name: 'gcr.io/cloud-builders/docker'
      args: ['ps']
    - id: "Run tests"
      name: 'gcr.io/cloud-builders/docker'
      waitFor: ['Run docker-compose']
      args: ['exec', '-t', 'gcb-pipelines', 'yarn', 'test']